### ISSUE TITLE
Placeholder issue for next npm version

### ISSUE THREAD

**Issue by jesseditson** [weo-edu/khan#3]
Hey there!

I just added this library as a dependency of https://github.com/jesseditson/passport-khan, but that library requires the latest PRs I filed against this one.

If you could just close this issue whenever you next publish, I'll update the dependencies on the above library to use the version from npm instead of pointing at my branch.

Thanks!

**Comment by ashaffer** [comment]
They're both merged and published :).  Thx for the PRs.

**Comment by jesseditson** [comment]
Ah wow, you're quick!

Thanks!
